import { BookOpenCheck, CheckCircle2, Gauge, MessageSquareText, Sparkles, Target } from 'lucide-react'
import type { Dispatch, SetStateAction } from 'react'
import type { DecisionLog, DecisionStatus, Evidence, InterviewRecord, Job } from '../domain/types'
import { buildMatches, ensureEvidenceReferences, resolveMatchesWithDecisions } from '../lib/engine'

export function InterviewReview({ job, evidence, decisions, interviews, setInterviews, recordDecision }: { job: Job; evidence: Evidence[]; decisions: DecisionLog[]; interviews: InterviewRecord[]; setInterviews: Dispatch<SetStateAction<InterviewRecord[]>>; recordDecision: (type: DecisionLog['targetType'], id: string, status: DecisionStatus, note?: string) => void }) {
  const jobRecords = interviews.filter((item) => item.jobId === job.id)
  const generate = () => {
    const matches = resolveMatchesWithDecisions(buildMatches(job, evidence), decisions, evidence)
    const questions = job.requirements.slice(0, 4).map((requirement, index): InterviewRecord => { const match = matches.find((item) => item.requirementId === requirement.id)!; const rejected = match.evidenceIds.length === 0; const generated = { id: `IV-${job.id}-${requirement.id}`, jobId: job.id, question: `请结合真实项目说明：你如何证明自己${requirement.text}？`, answer: '', evidenceIds: rejected ? [] : ensureEvidenceReferences(match.evidenceIds.slice(0, 1), evidence), confidence: match.confidence, weakness: rejected ? '该证据匹配已被人工驳回，需要补充新的真实项目证据。' : match.gap ?? '', nextAction: '', status: 'pending' as DecisionStatus }; const existing = jobRecords.find((item) => item.question === generated.question) ?? jobRecords[index]; return existing ? { ...generated, id: existing.id, answer: existing.answer, weakness: existing.weakness, nextAction: existing.nextAction, status: existing.status, evidenceIds: existing.status === 'pending' ? generated.evidenceIds : existing.evidenceIds } : generated })
    setInterviews((items) => [...items.filter((item) => item.jobId !== job.id), ...questions])
  }
  const update = (id: string, patch: Partial<InterviewRecord>) => setInterviews((items) => items.map((item) => item.id === id ? { ...item, ...patch } : item))
  const average = jobRecords.length ? Math.round(jobRecords.reduce((sum, item) => sum + item.confidence, 0) / jobRecords.length) : 0
  return <><section className="section-intro"><div><span className="section-kicker">06 / Interview Review</span><h1>复盘不是记流水账，<br />而是把薄弱点<strong>变成下一张证据。</strong></h1><p>保存问题、回答、引用项目、信心和补强行动，形成持续迭代。</p></div><button className="primary" onClick={generate}><Sparkles size={16} /> 生成面试问题</button></section><section className="interview-summary panel"><Summary icon={Target} label="当前岗位" value={job.title} note={job.company} tone="violet" /><Summary icon={BookOpenCheck} label="准备问题" value={String(jobRecords.length)} note="每题绑定真实证据" tone="cyan" /><Summary icon={Gauge} label="平均信心" value={`${average}%`} note="来自匹配置信度" tone="amber" /></section><section className="interview-list">{!jobRecords.length ? <div className="empty-state panel"><MessageSquareText size={30} /><h2>还没有这份岗位的面试准备</h2><p>从岗位要求自动生成问题，但回答必须由你填写，不能让 AI 伪造经历。</p><button className="primary" onClick={generate}>生成问题</button></div> : jobRecords.map((record, index) => <article className="interview-card panel" key={record.id}><header><span>QUESTION {String(index + 1).padStart(2, '0')}</span><span className="confidence">Confidence {record.confidence}%</span></header><h2>{record.question}</h2><label><span>我的回答</span><textarea placeholder="用 STAR 或问题—决策—结果结构记录真实回答……" value={record.answer} onChange={(event) => update(record.id, { answer: event.target.value, status: 'edited' })} /></label><div className="interview-fields"><label><span>暴露出的薄弱点</span><input value={record.weakness} onChange={(event) => update(record.id, { weakness: event.target.value })} placeholder="例如：缺少线上指标" /></label><label><span>下一步补强行动</span><input value={record.nextAction} onChange={(event) => update(record.id, { nextAction: event.target.value })} placeholder="例如：补评测集与错误案例" /></label></div><footer><div><span>Evidence:</span>{record.evidenceIds.map((id) => <em key={id}>{id}</em>)}</div><button onClick={() => { update(record.id, { status: 'accepted' }); recordDecision('interview', record.id, 'accepted') }}><CheckCircle2 size={15} />完成复盘</button></footer></article>)}</section></>
}

function Summary({ icon: Icon, label, value, note, tone }: { icon: typeof Target; label: string; value: string; note: string; tone: string }) { return <div><span className={`metric-icon ${tone}`}><Icon size={19} /></span><div><small>{label}</small><strong>{value}</strong><p>{note}</p></div></div> }
