import { ArrowUpRight, CheckCircle2, ExternalLink, FlaskConical, ShieldAlert, Target } from 'lucide-react'
import { interviewCapabilityMap, portfolioProjects, researchSources } from '../data/portfolioData'

export function ProjectCase() {
  return <>
    <section className="section-intro project-intro"><div><span className="section-kicker">00 / Project Case</span><h1>这不是虚构公司经历，<br />而是我的<strong>个人独立项目证据包。</strong></h1><p>所有“结果”只写可以由代码、测试、文档和在线 Demo 核验的交付；业务数据与真实用户效果明确标注为尚未验证。面试建议先讲 RoleProof，再用另外两个项目证明 B 端与情报场景迁移能力。</p></div><a className="primary" href="https://github.com/2392772541" target="_blank" rel="noreferrer">查看 GitHub <ArrowUpRight size={16}/></a></section>
    <section className="truth-banner panel"><ShieldAlert size={22}/><div><strong>真实性声明</strong><p>项目由本人作为个人作品完成。仓库中的公司、订单、职位、新闻与经营指标属于合成演示数据；测试数量、页面、代码、文档、提交记录和在线部署属于可核验交付。当前没有真实商业客户、收入或线上转化数据。</p></div></section>
    <section className="case-grid">{portfolioProjects.map((project,index)=><article className="case-card panel" key={project.id}><header><span>CASE {String(index+1).padStart(2,'0')}</span><strong>{project.name}</strong><p>{project.tagline}</p></header><div className="case-section"><small>问题与用户</small><p>{project.problem}</p><em>{project.users}</em></div><div className="case-section"><small>我的真实角色</small><p>{project.role}</p></div><div className="case-section"><small>关键产品决策</small><ul>{project.decisions.map(item=><li key={item}>{item}</li>)}</ul></div><div className="case-columns"><div><small>已交付</small><ul>{project.delivery.map(item=><li key={item}><CheckCircle2 size={13}/>{item}</li>)}</ul></div><div><small>可核验指标</small><ul>{project.verifiedMetrics.map(item=><li key={item}><FlaskConical size={13}/>{item}</li>)}</ul></div></div><div className="case-section limitation"><small>已知限制</small><ul>{project.limitations.map(item=><li key={item}>{item}</li>)}</ul></div><div className="capability-list">{project.interviewValue.map(item=><em key={item}>{item}</em>)}</div><footer>{project.proof.map(link=><a key={link.url} href={link.url} target="_blank" rel="noreferrer"><ExternalLink size={13}/>{link.label}</a>)}</footer></article>)}</section>
    <section className="panel capability-map"><div className="panel-heading"><div><h2>面试能力 → 项目证据映射</h2><p>面试时不要只讲功能，按“问题—决策—证据—边界”回答。</p></div></div><div className="capability-table"><div className="capability-row head"><span>面试能力</span><span>项目证据</span><span>现场演示</span><span>可能追问</span></div>{interviewCapabilityMap.map(item=><div className="capability-row" key={item.capability}><strong>{item.capability}</strong><span>{item.evidence}</span><span>{item.demo}</span><span>{item.interviewer}</span></div>)}</div></section>
    <section className="research-panel panel"><div><Target size={20}/><div><strong>岗位与评测研究来源</strong><p>以下链接用于持续核对岗位要求和 AI Evaluation 方法。岗位页面会变化，因此只把它们作为研究入口，不冒充本人投递记录。</p></div></div><div className="research-links">{researchSources.map(source=><a href={source.url} target="_blank" rel="noreferrer" key={source.url}><strong>{source.label}<ExternalLink size={12}/></strong><span>{source.note}</span></a>)}</div></section>
  </>
}
